// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

import java.io.*;
import simbad.sim.Agent;
import java.util.concurrent.TimeUnit;

/************************************************************/
/**
 * 
 */
public class CentralStation {
	/**
	 * 
	 */
	
	PrintStream out;
	
	private static CentralStation instance = new CentralStation();
	
	public static CentralStation getInstance() {
		return instance;
	}
	
	private CentralStation(){
		out = new PrintStream(System.out);
		numberOfRovers = 0;
		rovers = new Rover[20];
	}
	/**
	 * 
	 */
	private mapObject map;
	
	/**
	 * 
	 */
	private Rover[] rovers;
	
	/**
	 * 
	 */
	private RoverFactory factory;
	
	private int numberOfRovers;
	
	
	/**
	 * 
	 * @return
	 */
	public Rover[] getRovers() {
		return rovers;
	}

	/**
	 * 
	 * @return
	 */
	public mapObject getMap() {
		return map;
	}
	
	/**
	 * 
	 * @param map
	 */
	public void setMap(mapObject map) {
		this.map = map;
	}

	/**
	 * 
	 * @return  
	 */


	/**
	 * 
	 * @param mapSection 
	 */
	public void receiveMapSection(mapObject mapSection) {
	}

	/**
	 * 
	 * @param photoArray 
	 */
	public void receivePhotos(Photo[] photoArray) {
	}
	
	public void startCentralStation() {
		int iteration = 0;
		
		while (true) {
			out.print(iteration + "\n");
			for (int i = 0; i < numberOfRovers; i++) {
				out.print(rovers[i].getPosition() + "\n");
			}
			out.print("\n");
			try {
				TimeUnit.SECONDS.sleep(1);
			} catch (InterruptedException e) {
				e.printStackTrace();
			}
			iteration++;
		}
	}

	/**
	 * 
	 */
	public void initMappingStage() {
	}

	/**
	 * 
	 * @param mappingRover 
	 */
	public void initCameraStage(MappingRover mappingRover) {
	}

	/**
	 * 
	 * @param roverID 
	 */
	public void getRoverByID(int roverID) {
	}

	/**
	 * 
	 * @param roverID 
	 */
	public void indexNewRover(Rover rov) {
		rovers[numberOfRovers] = rov;
		numberOfRovers += 1;
	}
};
