// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

/************************************************************/
/**
 * 
 */
public class CentralStationAdapter {
	/**
	 * 
	 */
	public CentralStation centralstation;
	public Mission mission;

	/**
	 * 
	 * @param roverID 
	 * @param destination 
	 */
	public void moveRover(int roverID, Vector3D destination) {
	}

	/**
	 * 
	 * @param roverID 
	 */
	public void removeRover(int roverID) {
	}
};
