// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

import rovuClassDiagram1.ROVU.CentralStation;
import rovuClassDiagram1.ROVU.Vector3D;
import rovuClassDiagram1.ROVU.Mission;

/************************************************************/
/**
 * 
 */
public class CentralStationAdapter {
	/**
	 * 
	 */
	public CentralStation centralstation;
	public Mission mission;

	/**
	 * 
	 * @param roverID 
	 * @param destination 
	 */
	public void moveRover(int roverID, Vector3D destination) {
	}

	/**
	 * 
	 * @param roverID 
	 */
	public void removeRover(int roverID) {
	}
};
