// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

import javax.vecmath.Vector3d;

/************************************************************/
/**
 * 
 */
public class CO2Rover extends Rover {
	
	public CO2Rover(Vector3d arg0, String arg1) {
		super(arg0, arg1);
	}

	/**
	 * 
	 */
	private mapObject completeMap;
	/**
	 * 
	 */
	private CO2Level[] co2Levels;

	/**
	 * 
	 * @return
	 */
	public mapObject getCompleteMap() {
		return completeMap;
	}

	/**
	 * 
	 * @param completeMap
	 */
	public void setCompleteMap(mapObject completeMap) {
		this.completeMap = completeMap;
	}

	/**
	 * 
	 * @return
	 */
	public CO2Level[] getCO2Levels() {
		return co2Levels;
	}

	/**
	 * 
	 * @param photos
	 */
	public void setCO2Level(CO2Level[] co2Levels) {
		this.co2Levels = co2Levels;
	}

	/**
	 * 
	 */
	public void takeCO2Level() {
	}

	/**
	 * 
	 * @param completeMap 
	 */
	public void receiveMap(mapObject completeMap) {
	}

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void sendPhotos() {
	}
};
