// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

import rovuClassDiagram1.ROVU.CO2Level;
import rovuClassDiagram1.ROVU.Rover;
import rovuClassDiagram1.ROVU.mapObject;

/************************************************************/
/**
 * 
 */
public class CO2Rover extends Rover {
	/**
	 * 
	 */
	private mapObject completeMap;
	/**
	 * 
	 */
	private CO2Level[] co2Levels;

	/**
	 * 
	 * @return
	 */
	public mapObject getCompleteMap() {
		return completeMap;
	}

	/**
	 * 
	 * @param completeMap
	 */
	public void setCompleteMap(mapObject completeMap) {
		this.completeMap = completeMap;
	}

	/**
	 * 
	 * @return
	 */
	public CO2Level[] getCO2Levels() {
		return co2Levels;
	}

	/**
	 * 
	 * @param photos
	 */
	public void setPhotos(CO2Level[] co2Levels) {
		this.co2Levels = co2Levels;
	}

	/**
	 * 
	 */
	public void takeCO2Level() {
	}

	/**
	 * 
	 * @param completeMap 
	 */
	public void receiveMap(mapObject completeMap) {
	}

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void sendPhotos() {
	}
};
