// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

/************************************************************/
/**
 * 
 */
public enum Directions {
	/**
	 * 
	 */
	North,
	/**
	 * 
	 */
	South,
	/**
	 * 
	 */
	East,
	/**
	 * 
	 */
	West,
	/**
	 * 
	 */
	NorthEast,
	/**
	 * 
	 */
	NorthWest,
	/**
	 * 
	 */
	SouthEast,
	/**
	 * 
	 */
	SouthWest;
};
