// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

/************************************************************/
/**
 * 
 */
public class mapObject {
	/**
	 * 
	 */
	public Vector3D[] section;
	/**
	 * 
	 */
	public Vector3D[] obstaclesArray;
};
