// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

import rovuClassDiagram1.ROVU.Vector3D;

/************************************************************/
/**
 * 
 */
public class mapObject {
	/**
	 * 
	 */
	public Vector3D[] section;
	/**
	 * 
	 */
	public Vector3D[] obstaclesArray;
};
