// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

import javax.vecmath.Vector3d;

/************************************************************/
/**
 * 
 */
public class MappingRover extends Rover {
	public MappingRover(Vector3d arg0, String arg1) {
		super(arg0, arg1);
	}

	/**
	 * 
	 */
	private mapObject map;

	/**
	 * 
	 */
	public void updateMap() {
	}

	/**
	 * 
	 * @return  
	 */
	public boolean isDoneMapping() {
		return false;
	}

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void sendMap() {
	}

	/**
	 * 
	 * @return
	 */
	public mapObject getMap() {
		return map;
	}

	/**
	 * 
	 * @param map
	 */
	public void setMap(mapObject map) {
		this.map = map;
	}
};
