// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

import rovuClassDiagram1.ROVU.Rover;
import rovuClassDiagram1.ROVU.mapObject;

/************************************************************/
/**
 * 
 */
public class MappingRover extends Rover {
	/**
	 * 
	 */
	private mapObject map;

	/**
	 * 
	 */
	public void updateMap() {
	}

	/**
	 * 
	 * @return  
	 */
	public boolean isDoneMapping() {
		return false;
	}

	/**
	 * 
	 */
	public void start() {
	}

	/**
	 * 
	 */
	public void sendMap() {
	}

	/**
	 * 
	 * @return
	 */
	public mapObject getMap() {
		return map;
	}

	/**
	 * 
	 * @param map
	 */
	public void setMap(mapObject map) {
		this.map = map;
	}
};
