// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------


package ROVU;
import java.io.*;
import java.util.ArrayList;

import javax.vecmath.Vector3d;

import simbad.gui.Simbad;
import simbad.sim.Agent;

public class Mission {
	
	private int	numOfRoverTeams;
	private Environment environment;
	
	PrintStream out;
	
	Mission(Environment env) {
		out = new PrintStream(System.out);
		numOfRoverTeams = 4;
		out.print("Be Starting Missions All Day");
		environment = env;

	}
	
	Mission(int numbOfRoverTeams, Environment env) {
		numOfRoverTeams = numbOfRoverTeams;
		environment = env;
	}
		
	public CentralStation centralStation;
	
	/**
	 * 
	 */
	public void startMission() {
		centralStation = CentralStation.getInstance();
		
		addRoversToEnvironment();
		
		centralStation.initMappingStage();
		
		
	}
	
	/**
	 * 
	 * @param numRovers
	 */
	public void startMission(int numRovers) {
		
	}
	
	/**
	 * 
	 */
	public void stopMission() {
		
	}
	
	/**
	 * 
	 * @return
	 */
	public String getMissionStatus() {
		return "";
	}
	
	public void addRoversToEnvironment() {
		
        ArrayList<Agent> swarm = new ArrayList<Agent>();
        
        for (int i = 0; i < numOfRoverTeams; i++) {
        	MappingRover newMapBot = new MappingRover(new Vector3d(-3, 20, -3 + 2*i), "MappingRover " + i);
        	CameraRover newPhotoBot = new CameraRover(new Vector3d(-1, 20, -3 + 2*i), "PhotoRover " + i);
        	CO2Rover newCO2Bot = new CO2Rover(new Vector3d(1, 20, -3 + 2*i), "CO2Rover " + i);

        	
        	swarm.add(newMapBot);
        	centralStation.indexNewRover(newMapBot);
        	
        	swarm.add(newPhotoBot);
        	centralStation.indexNewRover(newPhotoBot);

        	swarm.add(newCO2Bot);
        	centralStation.indexNewRover(newCO2Bot);
        }
        
        for(Agent robot:swarm){
        	environment.add(robot);
        }
        
        new Simbad(environment, false);
        centralStation.startCentralStation();
	}
}
