// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

import rovuClassDiagram1.ROVU.Directions;
import rovuClassDiagram1.ROVU.Vector3D;

/************************************************************/
/**
 * 
 */
public class Photo {
	/**
	 * 
	 */
	public Vector3D coordinate;
	/**
	 * 
	 */
	public Directions direction;
};
