// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

/************************************************************/
/**
 * 
 */
public class Photo {
	/**
	 * 
	 */
	public Vector3D coordinate;
	/**
	 * 
	 */
	public Directions direction;
};
