// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package ROVU;

/************************************************************/
/**
 * 
 */
public class RoverFactory {

	/**
	 * 
	 * @param type 
	 * @return  
	 */
	public static Rover spawnRover(RoverType type) {
		Rover result = null;
		
		switch (type) {
			case MappingRover:
				//result =  new MappingRover();
				
			case CameraRover:
				//result = new CameraRover();
		}
		
		return result;
			
	}
};
