// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

import rovuClassDiagram1.ROVU.Rover;
import rovuClassDiagram1.ROVU.RoverType;

/************************************************************/
/**
 * 
 */
public class RoverFactory {

	/**
	 * 
	 * @param type 
	 * @return  
	 */
	public static Rover spawnRover(RoverType type) {
		Rover result = null;
		
		switch (type) {
			case MappingRover:
				result =  new MappingRover();
				
			case CameraRover:
				result = new CameraRover();
		}
		
		return result;
			
	}
};
