// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package rovuClassDiagram1.ROVU;

/************************************************************/
/**
 * 
 */
public enum RoverType {
	/**
	 * 
	 */
	CameraRover,
	/**
	 * 
	 */
	MappingRover;
};
